### ISSUE TITLE
Make footer to be at bottom

### ISSUE THREAD

**Issue by evghen1** [kndpio/website#13]
![screenshot-kndp io-2024 04 18-14_40_34](https://github.com/kndpio/website/assets/810573/2f411b20-7718-43cd-ab35-fb67f4b72f28)

**Comment by evghen1** [comment]
@BurlacuLucian Any news?

**Comment by BurlacuLucian** [comment]
> @BurlacuLucian Any news?

From docusaurus it is set so that the footer is applied immediately after the content and it is still inside the container, but if I change the sizes of this container in custom.css so that the height is always 100%, then the footer is applied normally but other styles from the navbar and sidebar are broken.

**Comment by evghen1** [comment]
@BurlacuLucian Please fix it asap.
